executable            = htc_run.sh
arguments             = $(ClusterId) $(ProcId)
output                = output/htc_run.$(ClusterId).$(ProcId).out
error                 = error/htc_run.$(ClusterId).$(ProcId).err
log                   = log/htc_run.$(ClusterId).log
request_CPUs          = 2
request_GPUs          = 1
+JobFlavour           = "testmatch"
+AccountingGroup      = "group_u_TE.mpe"
requirements          = regexp("V100", TARGET.CUDADeviceName)
queue 5