from src.API.XBox_class import *
import os

settings = {
    "dir_path": os.path.expanduser("~/project_data/CLIC_DATA_Xbox2_T24PSI_2/"),
    "dest_path": os.path.expanduser("~/output_files/"),
    "ed_ch_of_interest": ['DC Down',
                          'DC Up',
                          'PEI Amplitude',
                          'PEI Phase',
                          'PER log',
                          'PKI Amplitude',
                          'PKI Phase',
                          'PKR log',
                          'PSI Amplitude',
                          'PSI Phase',
                          'PSR Amplitude',
                          'PSR log',
                          'PSR Phase'],
    "td_ch_of_interest": ['Timestamp',
                          'Loadside win',
                          'Tubeside win',
                          'Collector',
                          'Gun',
                          'IP before PC',
                          'PC IP',
                          'WG IP',
                          'IP Load',
                          'IP before structure',
                          'US Beam Axis IP',
                          'Klystron Flange Temp',
                          'Load Temp',
                          'PC Left Cavity Temp',
                          'PC Right Cavity Temp',
                          'Bunker WG Temp',
                          'Structure Input Temp',
                          'Chiller 1',
                          'Chiller 2',
                          'Chiller 3',
                          'PKI FT avg',
                          'PSI FT avg',
                          'PSR FT avg',
                          'PEI FT avg',
                          'PKI max',
                          'PSI max',
                          'PSR max',
                          'PEI max',
                          'BLM TIA min',
                          'BLM min',
                          'DC Down min',
                          'DC Up min',
                          'BLM TIA Q',
                          'PSI Pulse Width',
                          'Pulse Count'],
    "number_of_workers_for_paralell_computation": 1
}

xb2ds = XBox2DataSet(settings)
xb2ds.transform(range(2))